name: noxstatus
author: Johan Eklund
copyright: Johan Eklund
maintainer: johan@meck.se
github: meck/noxstatus
version: 0.1.0.0
license: BSD3
description: Please see the README on GitHub at <https://github.com/meck/noxstatus#readme>

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - async
    - bytestring
    - http-client
    - http-types
    - http-conduit
    - aeson
    - time

tests:
  noxstatus-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - noxstatus

executables:
  noxstatus:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - optparse-applicative
      - directory
      - boxes
      - http-conduit
      - aeson
      - time
      - noxstatus
